Introduce data item model
fabric8-analytics/gremlin-docker pull request #12
Opened 2017-06-21 10:46 UTC by miteshvp

2017-06-21 10:46 UTC, miteshvp commented
@msrb - PTAL

2017-06-22 04:36 UTC, miteshvp commented
@msrb - can you take a look. We need this to perform load test for SINGLE data model

2017-06-22 07:38 UTC, msrb requested changes

2017-06-22 07:38 UTC, msrb commented on scripts/entrypoint.sh
> +    if grep -i 'storage.dynamodb.stores.edgestore.data-model=' "$PROPS" 1>/dev/null; then
This is going to match also commented out lines.

2017-06-22 08:07 UTC, msrb commented
Just one small issue, otherwise LGTM.

2017-06-22 08:36 UTC, miteshvp commented
Thanks. Done.

2017-06-22 08:49 UTC, msrb commented
LGTM, thanks ;)

2017-06-22 08:49 UTC, merged